name: dreamvision
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  go_router: ^16.2.2
  http: ^1.5.0
  logger: ^2.6.1
  google_nav_bar: ^5.0.7
  fl_chart: ^1.1.0
  syncfusion_flutter_charts: ^31.1.19
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.3.2
  file_picker: ^10.3.3
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  dio_cache_interceptor: ^4.0.5
  http_cache_hive_store: ^5.0.1
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  dropdown_search: ^6.0.2
  flutter_expandable_fab: ^2.5.2
  flutter_speed_dial: ^7.0.0
  syncfusion_flutter_xlsio: ^31.2.5
  file_saver: ^0.3.1
  open_filex: ^4.7.0
  permission_handler: ^12.0.1
  device_info_plus: ^12.2.0
  fluttertoast: ^9.0.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo.jpeg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/login_bg.png"